const instrumentToIconMap = {
  Guitar: "guitarra-electrica.svg",
  "Acoustic Guitar": "guitarra-acustica.svg",
  Bass: "bajo-electrico.svg",
  "Acoustic Bass": "bajo-acustico.svg",
  Ukulele: "ukulele.svg",
  Violin: "violin.svg",
  Viola: "viola.svg",
  Cello: "chelo.svg",
  "Double Bass": "contrabajo.svg",
  Banjo: "banjo.svg",
  Mandolin: "mandolin.svg",
  Harp: "arpa.svg",
  Trumpet: "trompeta.svg",
  Trombone: "trombon.svg",
  Tuba: "tuba.svg",
  "French Horn": "cuerno-frances.svg",
  Saxophone: "saxofon.svg",
  Clarinet: "clarinete.svg",
  Flute: "flauta.svg",
  Oboe: "oboe.svg",
  Bassoon: "fagot.svg",
  Recorder: "flauta.svg",
  Drum: "caja.svg",
  Cymbal: "plato.svg",
  "Drum set": "bateria.svg",
  "Electronic Drums": "bateria-electronica.svg",
  "Drum Pad": "bateria.svg",
  Percussion: "bongos.svg",
  "Small Percussion": "triangulo.svg",
  Keyboard: "teclado.svg",
  Piano: "piano.svg",
  Synthesizer: "teclado.svg",
  " Microphone": "teclado.svg",
  " Amplifier": "amplificador.svg",
  Speaker: "altavoz.svg",
  Monitor: "monitor.svg",
  Headphones: "headphones.svg",
  Light: "foco.svg",
  Other: "other.svg",
};

export default instrumentToIconMap;
