const instrumentToIconMap = {
  Guitarra: "guitarra-electrica.svg",
  "Guitarra acústica": "guitarra-acustica.svg",
  Bajo: "bajo-electrico.svg",
  "Bajo acústico": "bajo-acustico.svg",
  Ukulele: "ukulele.svg",
  Violín: "violin.svg",
  Viola: "viola.svg",
  Chelo: "chelo.svg",
  Contrabajo: "contrabajo.svg",
  Banjo: "banjo.svg",
  Mandolina: "mandolin.svg",
  Arpa: "arpa.svg",
  Trompeta: "trompeta.svg",
  Trombón: "trombon.svg",
  Tuba: "tuba.svg",
  "Corno francés": "cuerno-frances.svg",
  Saxofón: "saxofon.svg",
  Clarinete: "clarinete.svg",
  Flauta: "flauta.svg",
  Oboe: "oboe.svg",
  Fagot: "fagot.svg",
  "Flauta dulce": "flauta.svg",
  Tambor: "caja.svg",
  Plato: "plato.svg",
  Batería: "bateria.svg",
  "Batería electrónica": "bateria-electronica.svg",
  "Pad de batería": "bateria.svg",
  Percusión: "bongos.svg",
  "Percusión pequeña": "triangulo.svg",
  Teclado: "teclado.svg",
  Piano: "piano.svg",
  Sintetizador: "teclado.svg",
  Micrófono: "microfono.svg",
  Amplificador: "amplificador.svg",
  Altavoz: "altavoz.svg",
  Monitor: "monitor.svg",
  Audífonos: "cascos.svg",
  Foco: "foco.svg",
  Otro: "otro.svg",
};

export default instrumentToIconMap;
